### ISSUE TITLE
withing shadowRoot styles injection do not work

### ISSUE THREAD

**Issue by sashafirsov** [sashafirsov/html-demo-element#6]
See #5 for details

**Comment by sashafirsov** [comment]
@jogibear9988 ,
![image](https://github.com/user-attachments/assets/b782043e-f35b-4c86-9dc2-b2adb1dee35b)
the styles seems now applied.
but the code was injected over code panel, not in npm list.
```html
<script type="module" src="https://unpkg.com/html-demo-element@1.0.11/html-demo-element.js"></script>
<html-demo-element legend="with legend attribute 🤗" description="👓Description will be kept next to legend but less emphasized ">
    Eating own<code>dog food</code>🦴
</html-demo-element>
```

**Comment by jogibear9988** [comment]
yeah, but it will only work when loaded with a script tag, and only in the shadowroot where it was loaded....
because only there are the styles...

normaly I think the styles should be loaded via CSS Modules in a own shadowroot of your component

**Comment by sashafirsov** [comment]
I have tried with exact version in npm listing, seems working fine. The `latest` been refering previous for some reson, even after browser refresh.
![image](https://github.com/user-attachments/assets/1b18cd65-1a03-4e5e-ad27-2794e9ba2ec1)

![image](https://github.com/user-attachments/assets/650ad56b-e2c1-45db-b8d5-a824db8e5110)
